[package]
name = "radonlib"
version = "0.1.0"
edition = "2022"

[dependencies]
rand = "0.8.0"

[lib]
name = "radon-lib"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.14.4"
features = ["extension-module"]